import { Header } from "@/components";
import NavBar from "@/components/NavBar";
import Providers from "@/Providers";
import SessionProvider from "@/utils/SessionProvider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "svgmap/dist/svgMap.min.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Header />
          <Providers>{children}</Providers>
          <NavBar />
        </SessionProvider>
      </body>
    </html>
  );
}
